using PickleballScheduler.Models;

namespace PickleballScheduler.Services;

/// <summary>
/// Whist Cyclic schedule generator. For supported sizes (n = 8, 12, 16, 20, 24),
/// produces the first n-1 rounds of a Whist tournament: every pair partners
/// exactly once and every pair opposes exactly twice.
/// </summary>
internal static class WhistCyclicSchedule
{
    private static readonly HashSet<int> SupportedSizes = new() { 8, 12, 16, 20, 24 };

    public static bool IsSupportedSize(int playerCount) => SupportedSizes.Contains(playerCount);

    /// <summary>
    /// Returns matchups (no court numbers) for round <paramref name="roundIndex"/> (0-based,
    /// max <paramref name="players"/>.Count - 2) of the Whist Cyclic schedule.
    /// </summary>
    public static List<Match> GetRoundMatchups(List<Player> players, int roundIndex)
    {
        if (!IsSupportedSize(players.Count))
            throw new ArgumentException($"Unsupported player count: {players.Count}", nameof(players));
        if (roundIndex < 0 || roundIndex >= players.Count - 1)
            throw new ArgumentOutOfRangeException(nameof(roundIndex));

        var baseRound = BaseRounds[players.Count];
        var n = players.Count;
        var rotateMod = n - 1;

        var matches = new List<Match>(baseRound.Length);
        foreach (var bm in baseRound)
        {
            matches.Add(new Match
            {
                Team1Player1Id = ResolveRole(bm.A, roundIndex, rotateMod, players),
                Team1Player2Id = ResolveRole(bm.B, roundIndex, rotateMod, players),
                Team2Player1Id = ResolveRole(bm.C, roundIndex, rotateMod, players),
                Team2Player2Id = ResolveRole(bm.D, roundIndex, rotateMod, players),
            });
        }
        return matches;
    }

    private static int ResolveRole(string role, int roundIndex, int rotateMod, List<Player> players)
    {
        if (role == "inf") return players[0].Id;
        var i = int.Parse(role);
        var rotated = (i + roundIndex) % rotateMod;
        return players[1 + rotated].Id;
    }

    private record BaseMatch(string A, string B, string C, string D);

    // Verified by WhistCyclicScheduleTests.AllPairsPartnerOnceAndOpposeTwice.
    // Wh(8) is a textbook construction; Wh(12)-(24) were generated by the
    // brute-force search in WhistCyclicScheduleTests.GenerateBaseRound (skipped one-shot).
    private static readonly IReadOnlyDictionary<int, BaseMatch[]> BaseRounds =
        new Dictionary<int, BaseMatch[]>
        {
            // Wh(8): players ∞, 0..6. Rotation mod 7.
            [8] = new[]
            {
                new BaseMatch("inf", "0", "1", "3"),
                new BaseMatch("2",   "6", "4", "5"),
            },
            // Wh(12): players ∞, 0..10. Rotation mod 11.
            // Source: brute-force generator (see WhistCyclicScheduleTests.GenerateBaseRound).
            [12] = new[]
            {
                new BaseMatch("inf", "0", "1", "3"),
                new BaseMatch("2",   "9", "6", "7"),
                new BaseMatch("4",   "10", "5", "8"),
            },
            // Wh(16): players ∞, 0..14. Rotation mod 15.
            // Source: brute-force generator (see WhistCyclicScheduleTests.GenerateBaseRound).
            [16] = new[]
            {
                new BaseMatch("inf", "0",  "1",  "2"),
                new BaseMatch("3",   "6",  "9",  "11"),
                new BaseMatch("4",   "13", "8",  "12"),
                new BaseMatch("5",   "10", "14", "7"),
            },
            // Wh(20): players ∞, 0..18. Rotation mod 19.
            // Source: brute-force generator (see WhistCyclicScheduleTests.GenerateBaseRound).
            [20] = new[]
            {
                new BaseMatch("inf", "0",  "1",  "2"),
                new BaseMatch("3",   "5",  "9",  "15"),
                new BaseMatch("4",   "14", "17", "12"),
                new BaseMatch("6",   "18", "10", "13"),
                new BaseMatch("7",   "11", "16", "8"),
            },
            // Wh(24): players ∞, 0..22. Rotation mod 23.
            // Source: brute-force generator (see WhistCyclicScheduleTests.GenerateBaseRound).
            [24] = new[]
            {
                new BaseMatch("inf", "0",  "1",  "2"),
                new BaseMatch("3",   "14", "4",  "7"),
                new BaseMatch("5",   "20", "12", "17"),
                new BaseMatch("6",   "15", "21", "11"),
                new BaseMatch("8",   "10", "13", "19"),
                new BaseMatch("9",   "16", "18", "22"),
            },
        };
}
