namespace PickleballScheduler.Tests.Search;

internal static class CoverageCalculator
{
    public sealed record Result(int MaxCoverageRound, int SumCoverageRound, int[] CoverageRoundByPlayer);

    /// <summary>
    /// Simulates n-1 rounds of the Whist schedule generated by rotating the candidate.
    /// For each player p, returns the smallest 0-indexed round R such that across rounds 0..R,
    /// p has shared a court with every other player. If a player never reaches full coverage
    /// in n-1 rounds, that's a fatal validity issue — assertion fails.
    ///
    /// Uses bitmasks (n <= 32 fits in uint) for fast per-foursome updates and target checks.
    /// </summary>
    public static Result Compute(BaseRoundCandidate c) => Compute(c, pruneAtMaxRound: int.MaxValue);

    /// <summary>
    /// Branch-and-bound variant: returns a result with MaxCoverageRound == pruneAtMaxRound + 1
    /// (a sentinel meaning "no better than the cutoff") if any player has not reached full
    /// coverage by round pruneAtMaxRound. Use pruneAtMaxRound = int.MaxValue for no pruning.
    /// </summary>
    public static Result Compute(BaseRoundCandidate c, int pruneAtMaxRound)
    {
        int n = c.PlayerCount;
        int rotateMod = c.RotateMod;
        int rounds = rotateMod;

        if (n > 32)
            throw new InvalidOperationException("Bitmask coverage requires n <= 32");

        uint allOthersMask = n == 32 ? uint.MaxValue : (1u << n) - 1u;

        Span<uint> met = stackalloc uint[n];
        Span<int> coverage = stackalloc int[n];
        for (int p = 0; p < n; p++) { met[p] = 0u; coverage[p] = -1; }

        Span<int> court = stackalloc int[4];

        for (int r = 0; r < rounds; r++)
        {
            foreach (var m in c.Matches)
            {
                court[0] = ResolvePlayer(m.Team1A, r, rotateMod);
                court[1] = ResolvePlayer(m.Team1B, r, rotateMod);
                court[2] = ResolvePlayer(m.Team2A, r, rotateMod);
                court[3] = ResolvePlayer(m.Team2B, r, rotateMod);

                uint foursomeMask = (1u << court[0]) | (1u << court[1]) | (1u << court[2]) | (1u << court[3]);

                for (int i = 0; i < 4; i++)
                {
                    int p = court[i];
                    met[p] |= foursomeMask & ~(1u << p);
                }
            }

            uint targetMask;
            for (int p = 0; p < n; p++)
            {
                if (coverage[p] >= 0) continue;
                targetMask = allOthersMask & ~(1u << p);
                if (met[p] == targetMask) coverage[p] = r;
            }

            // Branch-and-bound: once r exceeds the cutoff, any player still uncovered means this
            // candidate cannot beat the current best. Return a sentinel result.
            if (r >= pruneAtMaxRound)
            {
                for (int p = 0; p < n; p++)
                    if (coverage[p] < 0)
                        return new Result(pruneAtMaxRound + 1, int.MaxValue, Array.Empty<int>());
            }
        }

        int max = 0, sum = 0;
        var coverageArr = new int[n];
        for (int p = 0; p < n; p++)
        {
            if (coverage[p] < 0)
                throw new InvalidOperationException(
                    $"player {p} did not reach coverage in {rounds} rounds — base round invalid");
            coverageArr[p] = coverage[p];
            if (coverage[p] > max) max = coverage[p];
            sum += coverage[p];
        }
        return new Result(max, sum, coverageArr);
    }

    private static int ResolvePlayer(int role, int round, int rotateMod)
    {
        if (role == BaseRoundCandidate.Inf) return 0;
        return ((role + round) % rotateMod) + 1;
    }
}
