namespace PickleballScheduler.Tests.Search;

internal static class CoverageCalculator
{
    public sealed record Result(int MaxCoverageRound, int SumCoverageRound, int[] CoverageRoundByPlayer);

    /// <summary>
    /// Simulates n-1 rounds of the Whist schedule generated by rotating the candidate.
    /// For each player p, returns the smallest 0-indexed round R such that across rounds 0..R,
    /// p has shared a court with every other player. If a player never reaches full coverage
    /// in n-1 rounds, that's a fatal validity issue — assertion fails.
    /// </summary>
    public static Result Compute(BaseRoundCandidate c)
    {
        int n = c.PlayerCount;
        int rotateMod = c.RotateMod;
        int rounds = rotateMod;  // n-1 rounds in canonical Whist cycle

        var met = new HashSet<int>[n];
        for (int p = 0; p < n; p++) met[p] = new HashSet<int>();

        var coverage = new int[n];
        for (int p = 0; p < n; p++) coverage[p] = -1;

        int target = n - 1;

        Span<int> court = stackalloc int[4];
        for (int r = 0; r < rounds; r++)
        {
            foreach (var m in c.Matches)
            {
                court[0] = ResolvePlayer(m.Team1A, r, rotateMod);
                court[1] = ResolvePlayer(m.Team1B, r, rotateMod);
                court[2] = ResolvePlayer(m.Team2A, r, rotateMod);
                court[3] = ResolvePlayer(m.Team2B, r, rotateMod);

                for (int i = 0; i < 4; i++)
                    for (int j = 0; j < 4; j++)
                        if (i != j) met[court[i]].Add(court[j]);
            }

            for (int p = 0; p < n; p++)
                if (coverage[p] < 0 && met[p].Count == target)
                    coverage[p] = r;
        }

        int max = 0, sum = 0;
        for (int p = 0; p < n; p++)
        {
            if (coverage[p] < 0)
                throw new InvalidOperationException(
                    $"player {p} did not reach coverage in {rounds} rounds (met {met[p].Count}/{target}) — base round invalid");
            if (coverage[p] > max) max = coverage[p];
            sum += coverage[p];
        }
        return new Result(max, sum, coverage);
    }

    private static int ResolvePlayer(int role, int round, int rotateMod)
    {
        if (role == BaseRoundCandidate.Inf) return 0;
        return ((role + round) % rotateMod) + 1;
    }
}
